//
//  CheckSeatsInteractor.swift
//  FlightRider
//
//  Created by Tomi on 2019. 11. 04..
//  Copyright (c) 2019. Tomi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CheckSeatsBusinessLogic
{
    func pushDataFromPreviousViewController(viewModel: SelectSeats.StoredData.CheckSeatsModel)
    func pushDataFromPreviousViewController(viewModel: ListFlights.CheckSeatsData.DataStore)
}

protocol CheckSeatsDataStore
{
    var dataStore: CheckSeats.DataStore.DataStore  { get set }
}

class CheckSeatsInteractor: CheckSeatsBusinessLogic, CheckSeatsDataStore
{
    var dataStore = CheckSeats.DataStore.DataStore()
    
    var presenter: CheckSeatsPresentationLogic?
    var worker: CheckSeatsWorker?
  
    // MARK: Push functions
    
    func pushDataFromPreviousViewController(viewModel: SelectSeats.StoredData.CheckSeatsModel) {
        dataStore.flight = viewModel.flight
        dataStore.justSelectedSeat = viewModel.justSelectedSeat
        dataStore.user = viewModel.user
    }
    
    func pushDataFromPreviousViewController(viewModel: ListFlights.CheckSeatsData.DataStore) {
        dataStore.flight = viewModel.flight
        dataStore.justSelectedSeat = viewModel.justSelectedSeat
        dataStore.user = viewModel.user
    }
  
}
