//
//  CheckSeatsModels.swift
//  FlightRider
//
//  Created by Tomi on 2019. 11. 04..
//  Copyright (c) 2019. Tomi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CheckSeats
{
  // MARK: Use cases
  
  enum DataStore
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct DataStore
    {
        var flight : ManagedFlight!
        var user : ManagedUser!
        var justSelectedSeat : Bool!
    }
  }
    
    enum GetAirplaneModel
    {
        struct Request
        {
            var airplaneType : String?
        }
        struct Response
        {
            var airplaneModel : AirplaneModel
        }
        struct DataStore
        {
        }
    }
    
    enum GetConstants
    {
        struct Request
        {
            let height : CGFloat
            let width : CGFloat
        }
        
        struct ViewModel
        {
            let viewSize: CGFloat
            let viewSpacing : CGFloat
            let lettersSpacing : CGFloat
            let fontSize : CGFloat
            let distanceFromTop : CGFloat
            let distanceFromLeading : CGFloat
            let distanceFromTrailing : CGFloat
            let seatNumbersViewSpacing : CGFloat
            let seatnumbersViewWidth : CGFloat
            let seatnumbersViewLeading : CGFloat
            let seatnumbersViewTop : CGFloat
            let seatnumbersViewBottom : CGFloat
            let cornerRadius : CGFloat
            
            init(request: CheckSeats.GetConstants.Request) {
                viewSize = request.width*0.0966
                viewSpacing = request.width*0.0169
                lettersSpacing = request.width*0.0724
                fontSize = request.width*0.0724
                distanceFromTop = request.height*0.0258
                distanceFromLeading = request.width*0.169
                distanceFromTrailing = request.width*0.1207
                seatNumbersViewSpacing = request.height*0.051
                seatnumbersViewWidth = request.width*0.0845
                seatnumbersViewLeading = request.width*0.0483
                seatnumbersViewTop = request.height*0.115
                seatnumbersViewBottom = request.height*0.06
                cornerRadius = viewSize*0.25
            }
        }
    }
    
    enum JustSelecetedSeatStatus
    {
        struct Request
        {
        }
        struct Response
        {
            var justSelectedSeat : Bool
        }
        struct DataStore
        {
        }
    }
}

