//
//  CheckSeatsModels.swift
//  FlightRider
//
//  Created by Tomi on 2019. 11. 04..
//  Copyright (c) 2019. Tomi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CheckSeats
{
  // MARK: Use cases
  
  enum DataStore
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct DataStore
    {
        var flight : ManagedFlight!
        var user : ManagedUser!
        var justSelectedSeat : Bool!
    }
  }
}
