//
//  SelectSeatsInteractor.swift
//  FlightRider
//
//  Created by Tomi on 2019. 10. 31..
//  Copyright (c) 2019. Tomi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SelectSeatsBusinessLogic
{
  func requestDisplayData(request: SelectSeats.DisplayData.Request)
  func pushDataFromPreviousViewController(viewModel: ListFlights.SelectSeatsData.ViewModel)
}

protocol SelectSeatsDataStore
{
    var viewModel : SelectSeats.StoredData.ViewModel { get set }
}

class SelectSeatsInteractor: SelectSeatsBusinessLogic, SelectSeatsDataStore
{
    
    var viewModel = SelectSeats.StoredData.ViewModel()
    
    //MARK: - Request functions
    
    func requestDisplayData(request: SelectSeats.DisplayData.Request) {
        let response = SelectSeats.DisplayData.Response(image: viewModel.image, flightNumber: viewModel.flight?.iataNumber)
        presenter?.fetchDisplayData(response: response)
    }
    
    //MARK: - Push functions
    
    func pushDataFromPreviousViewController(viewModel: ListFlights.SelectSeatsData.ViewModel) {
        self.viewModel.flight = viewModel.flight
        self.viewModel.user = viewModel.user
        self.viewModel.userRecord = viewModel.userRecord
        self.viewModel.image = viewModel.image
    }
    
  var presenter: SelectSeatsPresentationLogic?
  var worker: SelectSeatsWorker?

}
