//
//  SelectSeatsWorker.swift
//  FlightRider
//
//  Created by Tomi on 2019. 10. 31..
//  Copyright (c) 2019. Tomi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SelectSeatsWorkerProtocol
{
    func requestPickerInitialization(request: SelectSeats.PickerDataSource.Request)
}

class SelectSeatsWorker : SelectSeatsWorkerProtocol
{
    weak var interactor: SelectSeatsInteractor?
    
    
    // Request functions
    func requestPickerInitialization(request: SelectSeats.PickerDataSource.Request) {
        let path = Bundle.main.path(forResource: "AirplaneModels", ofType: "json")!
        let data = try? String(contentsOf: URL(fileURLWithPath: path))
        let jsonData = JSON(parseJSON: data!)
        let jsonArray = jsonData.arrayValue
        let response = SelectSeats.PickerDataSource.Response(dataSource: jsonArray)
        interactor?.fetchPickerDataSource(response: response)
    }
}
