//
//  SelectSeatsPresenter.swift
//  FlightRider
//
//  Created by Tomi on 2019. 10. 31..
//  Copyright (c) 2019. Tomi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SelectSeatsPresentationLogic
{
    func fetchDisplayData(response: SelectSeats.DisplayData.Response)
}

class SelectSeatsPresenter: SelectSeatsPresentationLogic
{
   
  weak var viewController: SelectSeatsDisplayLogic?
  
    func fetchDisplayData(response: SelectSeats.DisplayData.Response) {
        let viewModel = SelectSeats.DisplayData.ViewModel(image: response.image, flightNumber: response.flightNumber)
        viewController?.displayData(viewModel: viewModel)
    }
  

}
