//
//  SelectSeatsViewController.swift
//  FlightRider
//
//  Created by Tomi on 2019. 10. 31..
//  Copyright (c) 2019. Tomi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SelectSeatsDisplayLogic: class
{
    func fetchDataFromPreviousViewController(viewModel: ListFlights.SelectSeatsData.ViewModel)
    func displayData(viewModel: SelectSeats.DisplayData.ViewModel)
}

class SelectSeatsViewController: UIViewController, SelectSeatsDisplayLogic
{
    
    @IBOutlet weak var flightNr: UILabel!
    @IBOutlet weak var flightLogo: UIImageView!
    @IBOutlet weak var seat1Picker: UIPickerView!
    
  var interactor: SelectSeatsBusinessLogic?
  var router: (NSObjectProtocol & SelectSeatsRoutingLogic & SelectSeatsDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = SelectSeatsInteractor()
    let presenter = SelectSeatsPresenter()
    let router = SelectSeatsRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    interactor?.requestDisplayData(request: SelectSeats.DisplayData.Request())
  }
  
    //Fetch functions
    func fetchDataFromPreviousViewController(viewModel: ListFlights.SelectSeatsData.ViewModel) {
        interactor?.pushDataFromPreviousViewController(viewModel: viewModel)
    }
    
    //Display functions
    func displayData(viewModel: SelectSeats.DisplayData.ViewModel) {
        flightNr.text = viewModel.flightNumber
        flightLogo.image = viewModel.image
    }
}
