//
//  CannotCheckInModels.swift
//  FlightRider
//
//  Created by Tomi on 2019. 10. 31..
//  Copyright (c) 2019. Tomi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CannotCheckIn {
  // MARK: Use cases

  enum StoredData {
    struct Request {
    }
    struct Response {
        var iataNumber: String?
        var departureDate: Date?
        var image: UIImage?
    }
    struct ViewModel {
        var iataNumber: String?
        var departureDate: Date?
        var image: UIImage?
    }
  }

    enum CalculateTime {
        struct Request {
            var departureDate: Date?
        }
        struct Response {
            let days: String
            let hours: String
            let minutes: String
        }
        struct ViewModel {
        }
    }
}
