# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlightRider' do

  pod 'Firebase/Auth'

  target 'FlightRiderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlightRiderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
