# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlightRider' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'FlightRiderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlightRiderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
