//
//  ListFlightsInteractor.swift
//  FlightRider
//
//  Created by Tomi on 2019. 10. 31..
//  Copyright (c) 2019. Tomi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListFlightsBusinessLogic
{
  func doSomething(request: ListFlights.Something.Request)
}

protocol ListFlightsDataStore
{
  //var name: String { get set }
}

class ListFlightsInteractor: ListFlightsBusinessLogic, ListFlightsDataStore
{
  var presenter: ListFlightsPresentationLogic?
  var worker: ListFlightsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ListFlights.Something.Request)
  {
    worker = ListFlightsWorker()
    worker?.doSomeWork()
    
    let response = ListFlights.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
