//
//  LoginWorker.swift
//  FlightRider
//
//  Created by Tomi on 2019. 10. 29..
//  Copyright (c) 2019. Tomi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CloudKit

class LoginWorker
{
  func doSomeWork()
  {
  }
    
    func rememberMeSwitchChanged(email: String, password: String){
        let defaults: UserDefaults? = UserDefaults.standard
        defaults?.set(true, forKey: "ISRemember")
        defaults?.set(email, forKey: "SavedUserName")
        let saveResult = KeychainWrapper.standard.set(password, forKey: "SavedPassword")
        if !saveResult{
            print("Password save to keychain was unsuccessful")
        }
    }
    
    func switchOffIsRemember(){
        let defaults: UserDefaults? = UserDefaults.standard
        defaults?.set(false, forKey: "ISRemember")
    }
    
    func fetchStoredLoginData() -> LoginData{
        
        var loginData = LoginData()
        
        let defaults: UserDefaults? = UserDefaults.standard
        
        if (defaults?.bool(forKey: "ISRemember")) ?? false{
            loginData.email = defaults?.value(forKey: "SavedUserName") as? String ?? ""
            if let retrievedString = KeychainWrapper.standard.string(forKey: "SavedPassword"){
                loginData.password = retrievedString
            }
            loginData.switchedOn = true
        }
        else {
            loginData.switchedOn = false
        }

        return loginData
    }
    
    func saveRecords(records : [CKRecord]){
        let operation = CKModifyRecordsOperation(recordsToSave: records, recordIDsToDelete: nil)
        operation.savePolicy = .ifServerRecordUnchanged
        CKContainer.default().publicCloudDatabase.add(operation)
        print("success")
        
    }
}
