//
//  LoginPresenter.swift
//  FlightRider
//
//  Created by Tomi on 2019. 10. 29..
//  Copyright (c) 2019. Tomi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
  func presentSomething(response: Login.LoginFields.Response)
    //func setSwitchState(loginData : LoginData)
}

class LoginPresenter: LoginPresentationLogic
{
    /*func setSwitchState(loginData: LoginData) {
        if(loginData.switchedOn){
            viewController!.setRememberMeOn()
        }
        else{
            viewController!.setRememberMeOff()
        }
    }*/
    
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Login.LoginFields.Response)
  {
    let viewModel = Login.LoginFields.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
